## Vector, Matrix and Tensor

<img src="Tensor.jpeg" width="600" height="600">

## Make a vector in numpy

In [1]:
import numpy as np

v = np.array([5,2,1])

print(v)

print(v.shape)

[5 2 1]
(3,)


In [16]:
v[1]

2

In [2]:
v.shape

(3,)

In [3]:
v = np.array([[5,2,1]])

print(v.shape)

(1, 3)


In [4]:
print(v[0])

[5 2 1]


In [5]:
v_t = np.transpose(v)
print(v_t)
v_t.shape

[[5]
 [2]
 [1]]


(3, 1)

In [27]:
v = np.array([[5,2,1]])
print(v)

[[5 2 1]]


In [18]:
v[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [28]:
v[0][1]

2

In [23]:
v.shape

(1, 3)

## Make a matrix in numpy

In [36]:
v = np.array([[1,2,3],[2, 0, 1]])

print(v)

print(v.shape)

print(v.size)

[[1 2 3]
 [2 0 1]]
(2, 3)
6


In [37]:
v_t = np.transpose(v)
print(v_t)
print(v_t.shape)
print(v_t.size)

[[1 2]
 [2 0]
 [3 1]]
(3, 2)
6


## Arrange or Reshape the matrix (2D array or 2D Tensor)

In [38]:
v = np.array([[1,2,3],[2, 0, 1]])
print(v.reshape(3,2))

# By applying the following reshape, we transform the matrix into 3D Tensor

print(v.reshape(3,1,2))
print(v.reshape(-1,1,2))


[[1 2]
 [3 2]
 [0 1]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]
[[[1 2]]

 [[3 2]]

 [[0 1]]]


## Make a 3D Tensor in numpy

In [41]:
v = np.array([[[1., 2.,3.], [4.,5.,6.]], [[7.,8.,9.], [11.,12.,13.]]])

print(v)

# The first element of shape shows how many, and the second and third elements shows the dimension
print(v.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [11. 12. 13.]]]
(2, 2, 3)


In [40]:
print(v[0])

[[1. 2. 3.]
 [4. 5. 6.]]


In [42]:
print(v[1])

[[ 7.  8.  9.]
 [11. 12. 13.]]


In [43]:
print(v[2])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [44]:
print(v.size)

12


In [45]:
print(v.reshape(3,2,-1))

[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 11.]
  [12. 13.]]]


In [46]:
print(v.reshape(3,-1,1))

[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]]

 [[ 5.]
  [ 6.]
  [ 7.]
  [ 8.]]

 [[ 9.]
  [11.]
  [12.]
  [13.]]]


## Make a 4D Tensor in numpy

In [47]:
v = np.zeros((2, 3, 5, 5))

In [48]:
print(v)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


## Make 5D Tensor in numpy 

In [49]:
v = np.zeros((2, 2, 3, 5, 5))
print(v)
print(v[0][0].shape)
print(v[0][1].shape)
print(v[1][0].shape)
print(v[1][1].shape)

[[[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]]



 [[[[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]

   [[0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]
    [0. 0. 0. 0. 0.]]]


  [[[0. 0. 0. 0. 0.]
    [0. 

## Matrix multiplication  

https://www.khanacademy.org/math/precalculus/precalc-matrices/properties-of-matrix-multiplication/a/properties-of-matrix-multiplication

In [55]:
a = np.array([[4, 2, 3],[2, 0, 1]])

b = np.transpose(a)

c = np.dot(a,b)

print(c)

[[29 11]
 [11  5]]


## Sudo Inverse of matrix

In [56]:
pinv_a = np.linalg.pinv(a)

print(pinv_a)

[[-0.08333333  0.58333333]
 [ 0.41666667 -0.91666667]
 [ 0.16666667 -0.16666667]]


In [57]:
print(np.dot(a, pinv_a))

[[ 1.00000000e+00  7.77156117e-16]
 [-2.77555756e-17  1.00000000e+00]]


In [58]:
print(np.dot(pinv_a, a))

[[ 0.83333333 -0.16666667  0.33333333]
 [-0.16666667  0.83333333  0.33333333]
 [ 0.33333333  0.33333333  0.33333333]]


### Share your observation

- Matrix multiplication is not commutative, AB is different from BA

## Element-wise multiplication of matrix

In [65]:
import numpy as np
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
print(np.multiply(a,b))
print(np.multiply(b,a))
print(a*b)
print(b*a)

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
