## What we have learned in DS 1.1 as a Data Analyst? 

* Learned the principles of effective storytelling

* You begin making proposals and decisions based on analysis

* You Explorated Data Analysis (EDA), you focused on the basics of statistical inference, hypothesis testing, correlation

* Check this out as a good resource for Data Analyst/ Data Engineer/ Data Scientist roles:

https://www.springboard.com/blog/wp-content/uploads/2016/07/UltimateGuidetoDataScienceInterviews-1.pdf

## What we are going to learn in DS 2.1 which covers Machine Learning?

### what is machine learning?

* Use data and algorithm that predict or classify the useen upcoming data with acceptable accuracy

### Two major machine learning algorithm:

1. Supervised Learning

2. Unsupervised Learning

The supevised learning is used to do:

1. Regression --> Temporature prediction, stock market prediction, next purchased item prediction

2. Classification --> Is an email spam or not-spam, is dog in the image or cat, is a comment about a post positive or negative or neutral 

The unspurvised learning is used to do:

1. Cluster data into groups

2. Reduce the dimention of features

## Machine Learning Components:

<img src="Images/machine-learning.png">

## What Level of Math Do We Need for Machine Learning?

I do recommend to refresh or learn the following topics:

1. Calculus

2. Linear Algebra

3. Probability and styatistics

<img src="Images/intro_2.png" width="500">

## DS 1.1 and DS 2.1 Comparison

In DS 1.1, for example when use Titanic dataset, we were interested to explore the data:

1- How many female passenger survived at section C?

In DS 2.1, we are interested in predicting:

1- If we know a passenger was female, young, embarked at section C and her Pclass was 1, predict has she survived or not?

## Data Precrosessing for Machine Learning:

### Scaling, Normalization, One-hot encoding, Label encoding

Please read: https://www.tutorialspoint.com/machine_learning_with_python/machine_learning_with_python_quick_guide.htm

Please read: http://scikit-learn.org/stable/modules/preprocessing.html

http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.normalize.html

Also, look at the first page here: https://www.analyticsvidhya.com/infographics/Scikit-Learn-Infographic.pdf

## Activity: A two dimensional array (Matrix) X is given, write a function that:

- Subtract the minimum element of each column from all the elements of that column

- Then devide the result to the range of value for each column

Hint: range is the difference between the maximum element and minimum element of each column

In [3]:
import numpy as np

def max_min_s(X):
    return (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))

X_train = np.array([[1000.0, 2.0], [1500.0, 3.0]])
print(max_min_s(X_train))

[[0. 0.]
 [1. 1.]]


In [4]:
from sklearn import preprocessing

min_max_scaler = preprocessing.MinMaxScaler()
X_minmax = min_max_scaler.fit_transform(X_train)
print(X_minmax)

[[0. 0.]
 [1. 1.]]


In [9]:
import sklearn
print(sklearn.__version__)

0.19.1


## Activity: A two dimensional array (Matrix) X is given, write a function that:

- Subtract the mean element of each column from all the elements of that column

- Then devide the result to the standard deviation of value for each column

In [10]:
def standard_s(X):
    return (X - X.mean(axis=0)) /X.std(axis=0) 

print(standard_s(X_train))

[[-1. -1.]
 [ 1.  1.]]


In [6]:
standard_scaler = preprocessing.StandardScaler()
X_ss = standard_scaler.fit_transform(X_train)
print(X_ss)

[[-1. -1.]
 [ 1.  1.]]


## The Python package that we use for ML

Sklearn

The OOP paradigm for all Sklearn models: 
https://www.springboard.com/blog/wp-content/uploads/2016/07/UltimateGuidetoDataScienceInterviews-1.pdf

## ML Steps:

1- Data Reading and Cleaning

2- Data Preprocessing

3- Data Splitting

4- Model selection

5- Model Fitting

6- Model Evaluation

## How do we evalue the machine learning models?

For supervised learning it is possible to evaluate the model from train and test data

For regression, the evaluation metrics are:

1. Mean Squared Error (MSE)

2. Mean Absolute Error (MAE)

For classification, the evaluation metrics are:

1. Classification Accuracy

2. Classification Recall, Precision and F1 score


For unsupervised learning there are no systematic approach to evaluate the models but the are ways to do it  