## Linear Algebra

- Why we need Linear Algebra

    1- To solve a system of linear equations
    
    2- Most of machine learning models and all most all deep learning models need it



## Matrix-Vector and Matrix-Matrix Multiplication

- On piece of paper, multiply the following matrix-vector:

<img src="matrix_matrix.png" width="300" height="300">

- On piece of paper, multiply the following matrices:

<img src="matrix_vector.png" width="300" height="300">

## Verify your answer in Python using Numpy

In [48]:
A = np.array([[1, 2], [0, 1], [2, 3]])
v = np.array([[2], [6]])
print(A)
print(v)
print(np.dot(A, v))

[[1 2]
 [0 1]
 [2 3]]
[[2]
 [6]]
[[14]
 [ 6]
 [22]]


In [45]:
A = np.array([[1, 2], [0, 1], [2, 3]])
B = np.array([[2, 5], [6, 7]])
print(A)
print(B)
print(np.dot(A, B))

[[1 2]
 [0 1]
 [2 3]]
[[2 5]
 [6 7]]
[[14 19]
 [ 6  7]
 [22 31]]


## Question: Can we express linear regression in matrix-vector format?

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Running Distance in Mile
x = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
                         7.042,10.791,5.313,7.997,5.654,9.27,3.1])

# Water Drinks in Litre
y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
                         2.827,3.465,1.65,2.904,2.42,2.94,1.3])


## We can obtain the prediction vector as the following: 

In [3]:
w1 = 0.25163494 
w0 = 0.79880123 
y_pred = [w1*i + w0 for i in x]
print(y_pred)

[1.629196532, 1.905994966, 2.1827934, 2.4872716774, 2.5426313642, 1.84761565992, 3.25953930826, 2.3544084290800003, 2.7087104245999996, 1.34409414498, 2.57081447748, 3.51419386754, 2.13573766622, 2.81112584518, 2.2215451807599997, 3.1314571237999997, 1.578869544]


## Also, we can define our feature matrix as X and weight vector as w

In [31]:
# print(np.ones((len(x), 1)))
# print(np.transpose([x]))
# Concatenate two matrix column-wise 
X = np.concatenate((np.transpose([x]), np.ones((len(x), 1))), axis=1)
print(X)

[[ 3.3    1.   ]
 [ 4.4    1.   ]
 [ 5.5    1.   ]
 [ 6.71   1.   ]
 [ 6.93   1.   ]
 [ 4.168  1.   ]
 [ 9.779  1.   ]
 [ 6.182  1.   ]
 [ 7.59   1.   ]
 [ 2.167  1.   ]
 [ 7.042  1.   ]
 [10.791  1.   ]
 [ 5.313  1.   ]
 [ 7.997  1.   ]
 [ 5.654  1.   ]
 [ 9.27   1.   ]
 [ 3.1    1.   ]]


In [32]:
X.shape

(17, 2)

In [33]:
w = np.array([w1, w0])

In [35]:
np.dot(X, w)

array([1.62919653, 1.90599497, 2.1827934 , 2.48727168, 2.54263136,
       1.84761566, 3.25953931, 2.35440843, 2.70871042, 1.34409414,
       2.57081448, 3.51419387, 2.13573767, 2.81112585, 2.22154518,
       3.13145712, 1.57886954])

## Another way

In [42]:
v_ones = np.ones((1, len(x)))
print(v_ones)
X = np.array([x, np.ones((1, len(x)))])
print(X)
w = np.array([w1, w0])
np.dot(w, X)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[array([ 3.3  ,  4.4  ,  5.5  ,  6.71 ,  6.93 ,  4.168,  9.779,  6.182,
        7.59 ,  2.167,  7.042, 10.791,  5.313,  7.997,  5.654,  9.27 ,
        3.1  ])
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])]


array([[1.62919653, 1.90599497, 2.1827934 , 2.48727168, 2.54263136,
        1.84761566, 3.25953931, 2.35440843, 2.70871042, 1.34409414,
        2.57081448, 3.51419387, 2.13573767, 2.81112585, 2.22154518,
        3.13145712, 1.57886954]])

## Transpose of a Matrix or a Vector 

- In linear algebra, the transpose of a matrix is an operator which switches the row and column indices of the matrix by producing another matrix denoted as Aᵀ

<img src="matrix-transpose.jpg" width="300" height="300">

## Transpose the Matrix in Numpy

In [51]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## Norm of a vector

- We have different norm, here we mean L2-norm, which measures the length of a vector from origin

## Activity: what is the length of the following vector:

- v = [3, 4]

In [64]:
from numpy import linalg as LA
v = np.array([3, 4])
LA.norm(v)

5.0

## Activity: Show that norm of a vector is the sqrt of V*V.T

In [59]:
v = np.array([3, 4])
np.sqrt(np.dot(v,v.T))

5.0

## Activity: The distance between two vector u and v

<img src="norm.png" width="500" height="500">

In [63]:
u = np.array([1, 1])
v = np.array([2, 2])
r = np.array([3, 8])
print(LA.norm(u - v))
print(LA.norm(u - r))
print(LA.norm(v - r))

1.4142135623730951
7.280109889280518
6.082762530298219


## Resources:

- https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

- http://matrixmultiplication.xyz